version: '3.1'

services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes: 
      - ./pg-data/:/var/lib/postgresql
    network_mode: "host"
    
  mysql:
    image: mysql
    environment: 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
    volumes:
      - ./mysql-data/:/var/lib/mysql
      - ./create_mysql_base.ddl:/data/application/init.sql
    command: --init-file /data/application/init.sql --secure-file-priv=""
    network_mode: "host"

  scripts:
    build: ./py-script
    depends_on: 
      - mysql
      - postgres
    network_mode: "host"
    environment: 
      - DB_PASS=${DB_PASS}
      - DB_ROOT=${DB_ROOT}

volumes:
  pg-data:
  mysql-data: 